repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-vcs-permalinks
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
  - repo: https://github.com/batmac/pre-commit-zig
    rev: 3ee6c77
    hooks:
      - id: zig-fmt
      - id: zig-build
      - id: zig-build-test
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.1.0
    hooks:
      - id: stylua
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
