name: Build and Push Docker Image

on:
  release:
    types: [ published ]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    name: Build and push image from release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare metadata
        id: meta
        run: |
          IMAGE="ghcr.io/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY##*/}"
          TAG="${{ github.event.release.tag_name }}"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag }}
            ${{ steps.meta.outputs.image }}:latest
          build-args: |
            GH_REPO=${{ github.repository }}
            VERSION=${{ github.event.release.tag_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


